program         | palavra-reservada   
var             | palavra-reservada   
integer         | palavra-reservada   
real            | palavra-reservada   
begin           | palavra-reservada   
end             | palavra-reservada   
if              | palavra-reservada   
then            | palavra-reservada   
else            | palavra-reservada   
while           | palavra-reservada   
do              | palavra-reservada   
sistemacalculo  | identificador       
a               | identificador       
b               | identificador       
c               | identificador       
x               | identificador       
y               | identificador       
